### ISSUE TITLE
Categorias de filtros não aparecem.

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#106]
![categorias filtro](https://cloud.githubusercontent.com/assets/20709505/17278888/f47d2d8e-573d-11e6-9958-75d3c0b25749.PNG)

**Comment by lucasartacho** [comment]
Esta Issue continua ocorrendo, porém notei que não é sempre. 
Quando as categorias não aparecem e eu abro o 'inspect element' elas passam a aparecer.

**Comment by lucasartacho** [comment]
Acabei de reproduzir esta issue usando MacOS no Chrome também.

**Comment by juliosgarbi** [comment]
Consegui reproduzir e solucionar, removi um transition que estava bugando com o angular-animate.
