### ISSUE TITLE
Bloquear a rolagem do site até que o loading acabe

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#108]
Nos primeiros segundos de carregamento do site não é possível rolar a página, mas depois de um tempo o conteúdo abaixo de destaque começa a carregar e passa a ser possível a rolagem.

![loasding](https://cloud.githubusercontent.com/assets/20709505/17279092/f94fc858-5742-11e6-887c-cf06a4e952d4.PNG)

**Comment by juliosgarbi** [comment]
Esse problema já foi resolvido, será aplicado efetuado um deploy logo menos com o hot fix
