### ISSUE TITLE
Logo da ESPN com bordas noIE

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#109]
O logo a ESPN aparece com borda azul no IE 10

**Comment by lucasartacho** [comment]
Essa issue ainda está ocorrendo no IE10, @juliosgarbi ela deveria estar normalizada no stage, ou só no próximo deploy?

**Comment by juliosgarbi** [comment]
Deveria estar no stage. Farei mais alguns testes no ie10 e retorno.
