### ISSUE TITLE
Imagem aparece descentralizada dentro do card - IE10

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#112]
Imagem do lado esquerdo esta desalinhada

![image](https://cloud.githubusercontent.com/assets/1746652/17279378/bbb87278-5748-11e6-9025-4a37e3322381.png)

**Comment by juliosgarbi** [comment]
Fizemos diversos testes no IE10 e não conseguimos replicar esse erro, provavelmente ele foi resolvido ao resolver outros bugs de layout dos cards.
