### ISSUE TITLE
Menu de filtros aberto nao cabe no 1024x768 - IE10

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#113]
No IE10, o menu nao aparece por completo ( filtros + btn filtrar ) na primeira dobra, isso vale para filtros de modalidade e dia.

![image](https://cloud.githubusercontent.com/assets/1746652/17279425/ddbddb46-5749-11e6-938a-0cf5aae20caa.png)

**Comment by juliosgarbi** [comment]
@robsoncoelho se der o scroll o menu de filtro surge por completo? Fiz alguns testes aqui e não conseguimos colocar esse filtro em um espaço menor de height do que o atual, os elementos acabam de encavalando, se o menu não surgir mesmo com o scroll pensaremos em uma solução mais avançada. ( cc @juniormag )

**Comment by juliosgarbi** [comment]
Efetuei o teste no IE10 e verifiquei que se der o scroll para baixo o filtro fica visivel.
