### ISSUE TITLE
Filtro por dia nao funciona no IE10

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#114]
Fiz filtros por dia e nenhum deles aparecem no IE10, refiz os mesmos testes no chrome e funcionou.

![image](https://cloud.githubusercontent.com/assets/1746652/17279443/2aa00f60-574a-11e6-9124-bf066a0f1d03.png)

**Comment by juliosgarbi** [comment]
@robsoncoelho fizemos diversos testes no IE10 e conseguimos fazer todos os filtros. Provavelmente deve ter sido resolvido ao efetuar outros ajustes.
