### ISSUE TITLE
Loading eterno com Adguard ativado

### ISSUE THREAD

**Issue by KalebPortillo** [d3estudio/powerstats-static#12]
Quando deixo o Adguard ativado fica no loading eterno.
Estou anexando imagem com as duas coisas que o adguard esta bloqueando:

![screen shot 2016-07-28 at 3 45 45 pm](https://cloud.githubusercontent.com/assets/10066821/17225244/82f9d4ec-54da-11e6-8d57-37da1a6791ec.png)

**Comment by juniormag** [comment]
👍

**Comment by juliosgarbi** [comment]
Como isso é um problema muito especifico deixaremos para resolver em uma segunda fase.

**Comment by adaoraul** [comment]
Isso acontece porque é um requisição XHR (Ajax) para outro dominio e o Adblocker entende como uma tentativa de exibir propaganda e acaba bloqueando.

Isso se resolve pedindo para o pessoal da ESPN criar um subdominio api.espnpowerstats.com.br apontar para powerade-prod.us-east-1.elasticbeanstalk.com.

Pode fazer essa solicitação @juniormag?

**Comment by adaoraul** [comment]
@juniormag algum retorno sobre esse problema?

**Comment by KalebPortillo** [comment]
Nao esta mais dando essep problema com o adguard ativado aqui

**Comment by adaoraul** [comment]
@KalebPortillo valeu!
