### ISSUE TITLE
Link do share para o twitter manda para a home

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#122]
O link do share para o twitter que fico header do mobile manda para a home e não abre o box para fazer o compartilhamento do conteúdo.

**Comment by juliosgarbi** [comment]
@robsoncoelho Share no header do mobile? Você poderia gerar um print disso? No mobile não há share no header, apenas no menu.

**Comment by juliosgarbi** [comment]
Testei no IOS, Android, Chrome e safari, não consegui replicar o erro, provavelmente foi resolvido com algum outro bug fix
