### ISSUE TITLE
Texto da seção destaque está com a fonte muito pequena e está passando no limite da tela

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#125]
![captura de tela 2016-08-01 as 19 32 39](https://cloud.githubusercontent.com/assets/20709505/17311079/f67290e8-581e-11e6-96e7-f48bf229fe15.png)

**Comment by juliosgarbi** [comment]
Essa tarefa é mais facil o Yamada-san fazer já que ele que animou o destaque!

**Comment by ymikaeru** [comment]
Texto quebrado em 2 linhas conforme layout.
