### ISSUE TITLE
Adicionar URL encurtada nos shares

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#130]
-- ​*site*​: utilizar essas urls já parametrizadas:
p/ facebook bit.ly/2aO5uwQ
p/ twitter bit.ly/2aGq8wb

-- ​*você atleta*​
p/ facebook bit.ly/2aq74RG

-- ​*card*​ (já tínhamos alinhado)
p/ facebook: bit.ly/2aKW3gw
p/ twitter: bit.ly/2aGpOgI

**Comment by juliosgarbi** [comment]
Junior, você atleta e url do site é tranquilo para implementar, mas os cards vamos ter que gerar essa URL via API, já que o share de card card vai gerar uma URL diferente.
