### ISSUE TITLE
ODT - Quebra de layout em cabeçalho UOL

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#133]
Verificar com o novo header

EXPECTED:

É esperado que não exista quebra de layout no cabeçalho UOL.

ACTUAL:

Em Firefox acontece quebra de layout no cabeçalho da UOL.

![img_3](https://cloud.githubusercontent.com/assets/1690192/17343880/43c32c92-58d6-11e6-86fc-d15b53d7f717.png)

**Comment by juniormag** [comment]
Scope:Home
Category:User Interaction
Impact:Minor
Browser/Device(s):Mozilla Firefox
Operating system(s):Windows 8.1
Status:New

**Comment by juliosgarbi** [comment]
ajustado
