### ISSUE TITLE
ODT - Sempre que é aplicado um filtro são apresentados os resultados e o "Momento do dia"

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#134]
EXPECTED:

É esperado que os filtros não gerem resultados que estejam fora do parâmetro especificado.

ACTUAL:

Atualmente independente do filtro especificado a seção "Momento do dia" é apresentada.

**Comment by juliosgarbi** [comment]
Tentei replicar isso de diversas formas, efetuei todas as formas de filtros diferentes, só aparece o Momento do dia, se há algum card para ser exibido no dia, eu arrumei esse bug ontem provavelmente eles testaram antes do deploy
