### ISSUE TITLE
ODT - Após aplicar filtro para o dia 8, vídeo em destaque desaparece

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#135]
EXPECTED:

É esperado que o sistema mostre todas as informações de um filtro.

ACTUAL:

Após aplicar filtro para o dia 8, área de Destaque desaparece.

Scope:Home
Category:User Interaction
Impact:Major
Browser/Device(s):Moto G2, iPhone 6 Plus, Mozilla Firefox, Internet Explorer 11, Google Chrome
Operating system(s):iOS 9.3, Android 6.0, Windows 8.1
Status:New

**Comment by juliosgarbi** [comment]
ja foi resolvido
