### ISSUE TITLE
ODT -  Nos dispositivos mobile em modo paisagem, site apresenta quebra de layout no "Destaque"

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#136]
EXPECTED:

É esperado que o site não apresente quebras de layout.

ACTUAL:

No iPhone 6 Plus no modo paisagem, site apresenta quebra de layout no "Momento do Dia".

**Comment by lucasartacho** [comment]
Momento do dia está Ok.
O problema persiste no Destaque.
