### ISSUE TITLE
ODT - Alguns esportes estão apresentado quebra de layout em ícone

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#138]
EXPECTED:

É esperado que não exista quebra de layout em ícone de esporte.

ACTUAL:

Alguns esportes estão apresentado quebre de layout.

![img_10](https://cloud.githubusercontent.com/assets/1690192/17344332/144ffbaa-58d8-11e6-99b7-27556ab2506c.png)

**Comment by juliosgarbi** [comment]
resolvido.
