### ISSUE TITLE
QA Ogilvy Mobile - Há um ícone não identificado ao lado do logo da UOL.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#140]
Checar prints no ppt.

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 13 51 pm](https://cloud.githubusercontent.com/assets/4741623/17345548/f569ff2e-58dc-11e6-8db8-24813a863936.png)

**Comment by juliosgarbi** [comment]
Isso foi solucionado com o novo header do uol, provavelmente eles fizeram os testes antes de efetuarmos o deploy! <3
