### ISSUE TITLE
QA Ogilvy Mobile - Não aparece a ilustração animada do primeiro scroll.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#143]
Checar print no ppt e implementar versão dos destaques mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 16 39 pm](https://cloud.githubusercontent.com/assets/4741623/17345626/476cf984-58dd-11e6-8fd9-9727d4c47fb9.png)
