### ISSUE TITLE
QA Ogilvy Mobile - Não há conteúdo dentro do menu aberto

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#144]
Checar layout, implementar termos de uso e verificar layout mobile desse menu

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 17 38 pm](https://cloud.githubusercontent.com/assets/4741623/17345659/6ed3d95c-58dd-11e6-8378-d08f6f544578.png)

**Comment by juliosgarbi** [comment]
O menu já esta com o botão dos termos de uso implementado, só falta criar a tela que o @phillfer esta fazendo.
