### ISSUE TITLE
QA Ogilvy Mobile - No menu aberto os ícones das redes sociais estão menores e com cor diferente do indicado.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#147]
Checar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 28 56 pm](https://cloud.githubusercontent.com/assets/4741623/17345966/fbd7b688-58de-11e6-9371-5844373d99e3.png)
