### ISSUE TITLE
QA Ogilvy Mobile - Após o scroll a navegação dos dias deve aparecer sendo: Box azul, número do dia e uma seta que se move umas 3x para baixo indicando que há uma ação nesse box.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#148]
Checar ppt, documento de navegação e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 29 12 pm](https://cloud.githubusercontent.com/assets/4741623/17345973/061f6e2e-58df-11e6-96df-cdb3e8138ce2.png)

**Comment by juniormag** [comment]
Julio,

Aqui estamos sem a seta que ele deixaram no doc de navegação / layout e testei no meu iPhone não consegui nem navegar na timeline. Te mostro pessoalmente, me chama

**Comment by lucasartacho** [comment]
Sem a seta ainda.
