### ISSUE TITLE
QA Ogilvy Mobile - Navegação / O box com o número deve aparecer apenas quando o usuário passar totalmente o primeiro scroll.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#149]
Checar ppt e documento de navegação.

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 29 29 pm](https://cloud.githubusercontent.com/assets/4741623/17345981/0f60f9d0-58df-11e6-8f2f-c57796979fe9.png)
