### ISSUE TITLE
QA Mobile - O corte diagonal está invertido no primeiro scroll e não deveria ter o corte na parte inferior.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#150]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 29 42 pm](https://cloud.githubusercontent.com/assets/4741623/17345991/16c421e8-58df-11e6-8fa7-bb05de369695.png)
