### ISSUE TITLE
QA Mobile - Todos os textos testão errados quanto ao tamanho e diagramação. Favor, verificar o layout enviado.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#151]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 29 53 pm](https://cloud.githubusercontent.com/assets/4741623/17345994/1dfa8b32-58df-11e6-8d6d-a00cc802213c.png)
