### ISSUE TITLE
QA Ogilvy Mobile - As cores e o tamanho dos boxes com os dias disponíveis está diferente.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#152]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 30 08 pm](https://cloud.githubusercontent.com/assets/4741623/17345999/2682b5ea-58df-11e6-8dd4-861b24eaaae6.png)
