### ISSUE TITLE
QA Ogilvy Mobile - O Light box está com opacidade diferente e o menu deve ficar atraz do mesmo.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#153]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 30 31 pm](https://cloud.githubusercontent.com/assets/4741623/17346010/34bff366-58df-11e6-850c-339bf841c07a.png)
