### ISSUE TITLE
QA Ogilvy Mobile - O texto dos cards (descrição) está muito menor do que o do layout enviado.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#154]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 31 04 pm](https://cloud.githubusercontent.com/assets/4741623/17346026/48b81164-58df-11e6-9910-4eef08c5761d.png)

**Comment by juliosgarbi** [comment]
Resolvido junto com a #165
