### ISSUE TITLE
QA Ogilvy Mobile - O ícone “flip” não está em svg, portanto fica embaçado.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#155]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 31 24 pm](https://cloud.githubusercontent.com/assets/4741623/17346031/547301b2-58df-11e6-9e2b-6791e84b522b.png)

**Comment by juliosgarbi** [comment]
Removi a animação do flip, adicionei o flip em svg.
