### ISSUE TITLE
QA Ogilvy Mobile - Espaçamento dos textos nos cards está maior do que deveria. Favor verificar, pois eles são de extrema importancia para a visualização no mobile.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#156]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 31 40 pm](https://cloud.githubusercontent.com/assets/4741623/17346036/5dfaee5c-58df-11e6-8ee9-1df5771a6adb.png)

**Comment by juliosgarbi** [comment]
Efetuei pixel perfect em todos os cards.
