### ISSUE TITLE
QA Ogilvy Mobile - O ícone esta menor e sem a cor indicada. Quando o filtro está ativo, o mesmo deve ficar azul assim como no layout original.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#159]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 32 45 pm](https://cloud.githubusercontent.com/assets/4741623/17346091/8498e6d6-58df-11e6-99f5-f46889d6298f.png)

**Comment by juliosgarbi** [comment]
fechado em #162
