### ISSUE TITLE
QA Ogilvy Mobile - A barra com “modadelidade”, “dia” e “badge” deve flutuar com o scroll, além da área que está selecionada também ficar em bold e com a cor diferente

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#160]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 34 18 pm](https://cloud.githubusercontent.com/assets/4741623/17346127/bce18b92-58df-11e6-8f3f-5d81cd9cf2d1.png)
