### ISSUE TITLE
QA Ogilvy Mobile - A cor do botão filtrar está errada e ao termos um filtro selecionado não aparece o botão “Limpar Seleção”.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#161]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 34 39 pm](https://cloud.githubusercontent.com/assets/4741623/17346145/c88fe772-58df-11e6-812f-5a2f69e2d5e0.png)
