### ISSUE TITLE
QA Ogilvy Mobile - O ícone de “filtros” está deslocado do grid e ao ter a sessão de filtro ativada o mesmo icone deve ficar com a cor diferente indicando ao usuário que o filtro está ativo.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#162]
Verificar documento de navegação e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 35 16 pm](https://cloud.githubusercontent.com/assets/4741623/17346163/de42dcbe-58df-11e6-9c68-ddd8a5d73ea3.png)

**Comment by lucasartacho** [comment]
Ao ter a sessão de filtro ativada o mesmo ícone deve ficar com a cor diferente indicando ao usuário que o filtro está ativo.

**Comment by juliosgarbi** [comment]
Essa issue ja havia sido resolvida, testei aqui e esta 100%

![sem-titulo-1](https://cloud.githubusercontent.com/assets/4741623/17379593/7f559cc2-5999-11e6-8d1b-293caec64df2.jpg)
