### ISSUE TITLE
QA Ogilvy Mobile - A área “momento do dia” está menor do que o indicado no layout.

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#163]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 35 40 pm](https://cloud.githubusercontent.com/assets/4741623/17346174/ed5aa1d2-58df-11e6-90b7-bcc72e365fda.png)

**Comment by juliosgarbi** [comment]
resolvido #165
