### ISSUE TITLE
QA Ogilvy Mobile - A diagramação do título está errada no momento do dia

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#164]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 36 16 pm](https://cloud.githubusercontent.com/assets/4741623/17346208/01d131ee-58e0-11e6-823a-719461e5eeae.png)

**Comment by juliosgarbi** [comment]
resolvido #165
