### ISSUE TITLE
QA Ogilvy Mobile - O tamanho e diagramação da ilustração está errada. (seguir os jpgs enviados separadamente com cada uma delas) no momento do dia

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#165]
Verificar ppt e layout mobile

**Comment by juliosgarbi** [comment]
![screen shot 2016-08-02 at 6 36 41 pm](https://cloud.githubusercontent.com/assets/4741623/17346217/12908188-58e0-11e6-86e3-640bc157ff9d.png)
