### ISSUE TITLE
QA Ogilvy Desktop - Reduzir limite de texto descritivo de cada dia

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#176]
A área de conteúdo no canto esquerdo está errada. O corte diagonal não está do tamanho certo e os textos estão menores. Principalmente a “caixa do texto” em branco, ela é bem menor do que o apresentado (apareceria em 2 linhas e não em 1, por exemplo).

Se o texto descritivo que fica abaixo do dia for grande ele não pode ultrapassar as margens, nesse exemplo deve manter os limites do texto "futebol".

![screen shot 2016-08-03 at 1 02 06 pm](https://cloud.githubusercontent.com/assets/1746652/17372504/90cf67a4-597a-11e6-8d19-2ff83573e69f.png)

**Comment by ymikaeru** [comment]
![screen shot 2016-08-08 at 4 29 17 pm](https://cloud.githubusercontent.com/assets/344981/17493102/47451c96-5d85-11e6-9be9-f812d6b7e62b.png)

Corrigimos o tamanho da font do subtitle e a espessura da font.
Acredito que manter a margem do esporte pode gerar um problema. Segue exemplo da "Vela"
