### ISSUE TITLE
QA Ogilvy Desktop - Considerar os espaços entre os textos, acima e abaixo dos mesmos, conforme no layout.

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#182]
O espaço entre o titulo e a descrição nos cards estão muito próximos, aumentar um pouco. Outro ponto indicado é o espaçamento entre a descrição e a foto logo abaixo. Se possível aumentar um pouco também.

**Comment by juliosgarbi** [comment]
fixed
