### ISSUE TITLE
QA Ogilvy Desktop - O mouse over no ícone de share está errado. 

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#184]
Deveriam ser dois quadrados em outline com os icones menores, não um retangulo.

Cada icone deve ter um quadrado e não o retangulo englobando os dois.

![screen shot 2016-08-03 at 1 23 03 pm](https://cloud.githubusercontent.com/assets/1746652/17373182/828956b6-597d-11e6-9d96-21cf662ac49a.png)

**Comment by juliosgarbi** [comment]
fix in 1a0e56d942a7484f71aaa4cf6c7b60c17569cb02
