### ISSUE TITLE
Adicionar URL encurtada nos shares e revisar textos

### ISSUE THREAD

**Issue by juniormag** [d3estudio/powerstats-static#188]

**Comment by juliosgarbi** [comment]
@juniormag eu não recebi nenhum texto para o share do site, o share dos cards estão indo o texto de descrição, se não houver descrição ele puxa o subtitulo.

Você poderia me passar as URLs encurtadas do site?

**Comment by juliosgarbi** [comment]
Resolvido em outra issue, o twitter já esta sendo shareado com o texto certo e com a url encurtada.
