### ISSUE TITLE
QA Ogilvy Desktop - Os botões de filtrar estão com menores do que deveriam e com o texto maiores.

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#191]
Os botões de filtrar e limpar filtros precisam ser um pouco maiores.

Layout de referência:
![image](https://cloud.githubusercontent.com/assets/1746652/17373924/b53a45d6-5980-11e6-96c9-c178841eff23.png)

**Comment by phillfer** [comment]
@ymikaeru ajustei o tamanho dos botões. Quando puder, gera os sprites e dá close nesse issue por favor.

**Comment by ymikaeru** [comment]
Acabei de ajustar o tamanho dos sprites, vou fechar a issue.
