### ISSUE TITLE
Momento do Dia não aparece por inteiro na tela do mobile e triângulo azul está com a ponta quebrada.

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#198]
![screenshot_2016-08-03-19-36-53](https://cloud.githubusercontent.com/assets/20709505/17376326/79f49c5a-598b-11e6-876f-53f7f0da63ea.png)

**Comment by juliosgarbi** [comment]
O momento do dia não deve aparecer 100% em todos os mobiles, um dos ajustes que a olgivy nos pediu era para deixar o momentos do dia maior, pois ele estava pequeno, fixei igual ao layout nos 630px de altura, testado com pixel perfect.
