### ISSUE TITLE
Os links gerados no share de cards deixaram de funcionar. Deve ser por causa do 'carregar mais'.

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#217]
O link que devia ancorar no card compartilhado não funciona, um exemplo é o link http://espnpowerstats.com.br/#/defesa

**Comment by juliosgarbi** [comment]
fixed in be828aea25b42dab266b0305638016b37927b790

**Comment by lucasartacho** [comment]
#213
