### ISSUE TITLE
Edição do card com imagem só funciona com o card aberto.

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#226]

**Comment by mathportillo** [comment]
Funciona no Firefox. Por enquanto essa é a solução temporária até resolvermos os bugs piores.

**Comment by mathportillo** [comment]
A dica é tentar carregar a imagem do S3 por `CSS` ao invés de `img`.

**Comment by adaoraul** [comment]
Bug corrigido no admin!
