### ISSUE TITLE
Arrumar share do facebook

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#40]
![captura de tela 2016-07-29 as 15 48 20](https://cloud.githubusercontent.com/assets/20709505/17260865/2460515c-55a9-11e6-80af-00066bae059a.png)

**Comment by juliosgarbi** [comment]
Bug solucionado na issue #26

**Comment by lucasartacho** [comment]
![captura de tela 2016-08-01 as 17 02 37](https://cloud.githubusercontent.com/assets/20709505/17307071/ac55439e-5809-11e6-83f9-cf753f19808f.png)

**Comment by juliosgarbi** [comment]
Lucas, efetuei o teste aqui e esta funcionando, o problema é que como o app esta em sandbox não é possivel sharear se não for adicionado no app, amanha adiciono todos para testarmos o você atleta.
