### ISSUE TITLE
Encurtar URLs de share do Twitter

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#42]

**Comment by lucasartacho** [comment]
O link ainda não aparece encurtado, neste exemplo só a URL come 23 caracteres.

![captura de tela 2016-08-01 as 19 51 16](https://cloud.githubusercontent.com/assets/20709505/17311366/3b0e01d6-5821-11e6-90e3-98c686c838b9.png)

**Comment by juliosgarbi** [comment]
@lucasartacho , deixarei essa issue aberta, mas não resolveremos agora, para colocar encurtador de URL terei que fazer o share pela API atualmente estamos fazendo o share pelo link de share. Resolverei futuramente.

**Comment by juliosgarbi** [comment]
isso ja é feito pelo twitter, só não parece quando estamos digitando a msg, mas quando enviamos ele encurta, da para ver na quantidade de caracteres restantes na imagem que eu estou postando.

![imgencurtador](https://cloud.githubusercontent.com/assets/4741623/17378528/aba70a18-5994-11e6-9314-9b96667808ce.jpg)
