### ISSUE TITLE
404 Not Found nos links de share dos Cards no twitter

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#43]
![captura de tela 2016-07-29 as 16 33 12](https://cloud.githubusercontent.com/assets/20709505/17261004/0d873378-55aa-11e6-8057-c6591afe7157.png)

**Comment by juliosgarbi** [comment]
@mathportillo você havia configurado isso? Eu testei tanto em homologação quanto local os dois deu acesso negado ou 404.

**Comment by juliosgarbi** [comment]
Esse problema ocorre pois o servidor de stage não esta configurado, mas ja solicitamos essa configuração
