### ISSUE TITLE
Quando volto pro inicio do site a barra de menu fica travada no topo por um tempo antes de se ajustar abaixo dos headers

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#48]
![bugtop_0](https://cloud.githubusercontent.com/assets/20709505/17261702/9589e57e-55ad-11e6-8e4c-5af12bc4a0cc.jpg)

**Comment by juliosgarbi** [comment]
Não consegui replicar.

**Comment by adaoraul** [comment]
Realizei alguns testes e não consegui replicar o erro, talvez tenha sido corrigido em alguma refatoração feita. @lucasartacho quer tentar replicar o erro e se não der em nada, pode fechar a tarefa?

**Comment by mathportillo** [comment]
Esse é um limite deliberado do mac de só disparar o evento `scroll` no safari no final do scroll,  é uma preferência visando performance mas limitando uso do evento.

A única saída é usar plugins em javascript para administrar o scroll, e não deixar o OS / Safari cuidarem disso sozinhos. O problema é que o overhead de processamento pra isso é grande, e o site já exige muita performance. A consequência é que usando javascript fica pior ainda, deixando todo o scroll lento, e não só o update da navbar.

Alguém tem outra saída @adaoraul @phillfer @lucasartacho?
O que acha @juniormag?

**Comment by adaoraul** [comment]
+1

**Comment by phillfer** [comment]
+1

**Comment by juniormag** [comment]
+1 

Se ele vai ficar travado e piorar a performance como o @mathportillo comentou, acho que não vale a pena.

Vamos seguir 💪
