### ISSUE TITLE
ScrollTop quando clica nos links das datas não estão considerando o header fixo

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#50]
Quando clica nas datas no menu esquerdo, ele manda um scrollTop para a sessão daquela data, porém o scrollTop não está considerando o header fixo, então aparece meio sobreposta a sessão....anexando foto para exemplificar.

(https://cloud.githubusercontent.com/assets/1746652/17262204/72e97252-55b0-11e6-95a2-b80fcef3e6fa.png)

**Comment by juniormag** [comment]
O scroll top deveria levar o usuário para o topo de um dos destaques dos dias que é um outro bug mas vou colocar junto com esse! 👊

**Comment by juliosgarbi** [comment]
Bug solucionado em #24 ;)
