### ISSUE TITLE
Ordem dos filtros de datas não aparecem ordenadas

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#53]
As datas aparecem fora de ordem cronológica. Obs.: Cliquei nas datas na mesma ordem que aparecem no filtro :)
![screen shot 2016-07-29 at 5 28 29 pm](https://cloud.githubusercontent.com/assets/1746652/17262555/809bc0e2-55b2-11e6-90f5-d21f861f44cd.png)

**Comment by juniormag** [comment]
Rob,

Aqui a ordem tem que ser a de seleção do usuário, então se ele clicou em (DIA5), (DIA19) e (DIA1) deve aparecer nessa mesma ordem.

Se for algo diferente disso que entendi pode retornar aqui ;)

👊

**Comment by robsoncoelho** [comment]
Era isso mesmo Júnior. fechou :)
