### ISSUE TITLE
Página não volta para a data atual quando o filtro por datas é retirado

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#55]
Quando colocamos um filtro por data e depois retirarmos ele, a página continua mostrando as informações apenas daqueles dias que foram filtrados e não da data atual.

**Comment by juliosgarbi** [comment]
Fiz diversos testes, mas não consegui replicar!

**Comment by robsoncoelho** [comment]
Erro meu, retirei o filtro e não cliquei no botão "Filtrar" novamente para ele atualizar a página.
