### ISSUE TITLE
Data no menu esquerdo se mantém fixa após filtrar por data específica

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#56]
Quando usamos o scroll para navegar inicialmente, o menu na esquerda aparece com a data que corresponde a informação apresentada, porém se abro o menu e filtro por uma data em específico, a data que estava aparecendo no menu anteriormente não some de imediato, somente se dou scroll na página esse menu de datas é atualizado.

O comportamento acontece no seguinte cenário:

1. Carregar a página e dar scroll até aparecer o menu esquerdo com as datas.
2. Filtrar por uma data que não seja a mesma que esteja aparecendo atualmente no menu
3. Clicar em filtrar

Assim que clicar em filtrar o menu de filtros se fecha e no menu lateral esquerdo ainda continua mostrando a data anterior.

**Comment by juliosgarbi** [comment]
Esse problema foi resolvido automaticamente ao resolver a issue:
Filtro: Quando aplico um filtro deveria voltar para o topo #30
