### ISSUE TITLE
Frame do video aparece antes de iniciar video pelo segunda vez

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#57]
Quando vc visualiza o video do "Momento do dia" uma vez e clica novamente no botão "assista agora" um frame do video aparece antes de reproduzir o video do início.

Testei com o video das partidas de tênis.

**Comment by juliosgarbi** [comment]
Esse é um comportamento comum do player, como estamos utilizando o youtube é como um preloader do conteudo.
