### ISSUE TITLE
Âncora para as datas estão desalinhadas

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#61]
As âncoras para as datas estão desalinhadas, um exemplo é quando tenho várias datas no menu lateral e clico na data menos recente, após a animação de scroll ele posiciona a página em um ponto errado.

Enviei uma foto no qual o scroll deveria apontar para o banner do dia 5, porém ele manda para uma área um pouco acima do que deveria.

![screen shot 2016-07-29 at 6 51 16 pm](https://cloud.githubusercontent.com/assets/1746652/17264562/36f70ba2-55be-11e6-95da-12ed4644a5fc.png)

**Comment by juliosgarbi** [comment]
Ao resolver a issue #24 essa foi resolvida automaticamente.
