### ISSUE TITLE
Data aparece atrás do conteúdo quando fazemos um swipe down

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#63]
A data aparece atrás do conteúdo quando fazemos um swipe down no iPhone.
![img_0241](https://cloud.githubusercontent.com/assets/1746652/17265178/28c82278-55c3-11e6-8e00-1aea265a2348.PNG)

**Comment by juniormag** [comment]
🚨  Prioridade Alta

**Comment by juliosgarbi** [comment]
Problema resolvido ao resolver outros bugs com o menu de navegação por dia.
