### ISSUE TITLE
Titulo aparece em cima da categoria no card

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#65]
Alguns titulos estão aparecendo em cima da categoria dentro do card.
![img_0244](https://cloud.githubusercontent.com/assets/1746652/17265345/875fda00-55c4-11e6-9475-2eeb35124e5a.PNG)

**Comment by juliosgarbi** [comment]
Issue resolvida ao resolver outros problemas de layout no mobile
