### ISSUE TITLE
Data está aparecendo embaixo da imagem de destaque

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#66]
A data está aparecendo embaixo da imagem em destaque, em alguns casos a data pode não ficar visível se a imagem for grande.

![img_0245](https://cloud.githubusercontent.com/assets/1746652/17265387/f069e964-55c4-11e6-8ad4-012149f72f09.PNG)

**Comment by juliosgarbi** [comment]
Issue resolvida ao resolver outros problemas de layout no mobile
