### ISSUE TITLE
Texto descritivo dentro do card está ultrapassando as margens laterais

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#67]
O texto que descreve o card está ultrapassando as margens laterais, ficando cortados. iPhone 5s

![img_0247](https://cloud.githubusercontent.com/assets/1746652/17265471/a556c5ea-55c5-11e6-93ce-71b8e8903d7c.PNG)

**Comment by juliosgarbi** [comment]
Fizemos a animação e a diagramação dos elementos seguindo o padrão da arte que é apenas um breve sub titulo do assunto, teremos que definir com o responsavel da implementação do conteudo que não poderá passar de 1 linha, a animação de todos os cards foram feitas pensando nisso.
