### ISSUE TITLE
Desabilitar o scroll na tela de loading 

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#68]

**Comment by juniormag** [comment]
👍

**Comment by lucasartacho** [comment]
A seção de loading esta em 100%vh, mas como no mobile tem a questão da barra de URL ele da uma quebrada quando dou scroll. Talvez bloqueando o scroll do conteúdo que está por trás da tela de loading funcione. (funcionou na issue #116)


![13901876_1135840969821686_192297952_o](https://cloud.githubusercontent.com/assets/20709505/17300428/c3f9bb68-57e8-11e6-88ff-c0523bf21235.png)
