### ISSUE TITLE
Textos com animação de corte dentro dos cards ficam distorcidos

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#72]
Os textos com a animação de corte que ficam dentro dos cards ficam desalinhados em alguns momentos. Isso aconteceu em quase todas as vezes que atualizei o navegador porém não ocorre em todos os cards. iPhone 5s

![img_0246](https://cloud.githubusercontent.com/assets/1746652/17265520/0cec2c18-55c6-11e6-8651-640a7cdbdec4.PNG)

**Comment by juniormag** [comment]
👍

**Comment by juliosgarbi** [comment]
Tive que remover as animações do IOS com isso os cortes foram resolvidos.
