### ISSUE TITLE
A lista de categorias de filtro quebra quando selecionada uma modalidade, o elemento que causa isto é o numero ao lado.

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#73]
![screenshot_2016-07-29-23-20-02](https://cloud.githubusercontent.com/assets/20709505/17265542/39072b86-55c6-11e6-9a69-b9f820195a70.png)

**Comment by juliosgarbi** [comment]
Essa issue ja foi arrumada.
