### ISSUE TITLE
Alguns cards estão com a tag da modalidade por cima do título. 

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#81]
![screenshot_2016-07-30-00-19-24](https://cloud.githubusercontent.com/assets/20709505/17265646/e9b683f0-55c6-11e6-94a8-b45ca4638db3.png)

**Comment by juniormag** [comment]
👍

**Comment by juliosgarbi** [comment]
Issue ajustada junto com outros diversos ajustes de layout no mobile.
