### ISSUE TITLE
Menu lateral esquerdo não faz scroll corretamente no iPhone 5s

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#87]
O menu lateral com as datas não está funcionando muito bem no iPhone 5s, quando eu tento fazer um swipe para visualizar as datas o menu não responde com os comandos, as vezes faço swipe para baixo e o menu faz o inverso.

**Comment by juniormag** [comment]
👍

**Comment by juliosgarbi** [comment]
issue resolvida junto com a #94
