### ISSUE TITLE
Deixar seção de menu e de filtro fixas na tela. 

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#92]

**Comment by juniormag** [comment]
Falcart, na tela de filtros?

**Comment by lucasartacho** [comment]
Na tela de menu mesmo. Tem os itens 'Você Olímpico' e 'Termos de Uso' um espaço vazio embaixo, rolando vemos os botões de compartilhamento e rolando mais ainda sobra mais uma área vazia.

**Comment by juliosgarbi** [comment]
issue resolvida no commit d80cb342b12815c8661162063c10c9537e2d53fa

**Comment by juliosgarbi** [comment]
@lucasartacho, esse problema foi resolvido, nós não podemos bloquear a barra da uol, ela faz parte do menu, mas quando damos o scroll no limite da barra do uol, o site trava e não é mais possivel scrollar.

**Comment by lucasartacho** [comment]
Beleza @juliosgarbi, na real o que ta acontecendo é que quando rolo a tela do menu ela vai ficando pra cima e só os botões de share ficam fixos. 

![screenshot_2016-08-03-21-51-32](https://cloud.githubusercontent.com/assets/20709505/17380700/d35db566-599e-11e6-93b6-e17e48fa71a4.png)
 
Se for isso que já ta resolvido desconsidera.

**Comment by lucasartacho** [comment]
Conforme vimos no Galaxy S5 o mesmo ocorre na tela de filtro.

**Comment by lucasartacho** [comment]
Erro persiste.
