### ISSUE TITLE
Deixar todo conteúdo do menu visível em uma tela só. Considerar height 100% menos a altura do header. 

### ISSUE THREAD

**Issue by lucasartacho** [d3estudio/powerstats-static#93]
Os botões de Share estão escondidos, só consigo vê-los ao dar scroll.

**Comment by juniormag** [comment]
Consegue mandar um print desse falcart?

**Comment by lucasartacho** [comment]
Pra essa tela em especial seria interessante considerar a altura do header(uol+espn+powerstats) para deixar tudo visível em uma tela só, sem a necessidade do scroll. 
![screenshot_2016-07-30-01-36-56](https://cloud.githubusercontent.com/assets/20709505/17266263/7eb14fda-55cc-11e6-904d-ffa3c389f53f.png)

**Comment by juliosgarbi** [comment]
issue resolvida no commit d80cb342b12815c8661162063c10c9537e2d53fa
