### ISSUE TITLE
Menu lateral aparece com mais de uma data no iPhone 5s

### ISSUE THREAD

**Issue by robsoncoelho** [d3estudio/powerstats-static#94]
O menu lateral aparece com mais de uma data em alguns momentos no iPhone 5s. Quando vc faz o swipe e clica em algumas datas as vezes ele aparece mais de uma opção na data atual, talvez isso se resolva quando corrigir a navegação meio desordenada do menu no 5s, que já foi listada em outra issue.

![img_0249](https://cloud.githubusercontent.com/assets/1746652/17266008/292bfba2-55ca-11e6-8e40-28f82bf3f575.PNG)

**Comment by juniormag** [comment]
✌️
