### ISSUE TITLE
Meu iphone não aguentou os motions dos cards

### ISSUE THREAD

**Issue by joaomarcosdesouza** [d3estudio/powerstats-static#95]

**Comment by juniormag** [comment]
@juliosgarbi Precisamos testar isso depois das melhorias de processamento que você está fazendo. Caso o processamento continue pesado podemos retirar todos o motion e apenas no mobile dar um fade nos cards de acordo com a rolagem para ficar mais leve 👊

**Comment by juliosgarbi** [comment]
A problema dessa issue na verdade não é processamento, o até o IOS7 existe um " bug " no safari que contabiliza o scroll apenas no fim dele e não durante, quando damos o scroll no iphone da a impressão de estar lagando, mas na verdade é que o card é baseado no posicionamento do scroll, quando ele é contabilizado acaba passando varios cards ao mesmo tempo e animando todos de forma desorganizada. Passei algumas horas procurando uma solução para isso, mas não consegui, vi nas notas de atualização da apple que isso foi corrigido no IOS8. Amanha procurarei mais alguma solução para isso, mas acredito que teremos que pensar em uma modo alternativo de tratar site no iphone já que ele é totalmente baseado em scroll position.

**Comment by juliosgarbi** [comment]
Infelizmente, como eu expliquei no comentario anterior o IOS tem um bug no scroll, a solução foi remover todas as animações e dependencias de scroll no IOS, já que não há reconhecimento do em real time do mesmo.
